version: "3"
services:
  nefele_api:
    container_name: nefele
    image: nefele/nefele
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'