name: 'Nefele Build and Test'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    
    - name: Run Docker Compose test
      run: docker-compose run -e CI=true -e JWT_SECRET=asdf -e MONGO_URI=mongodb://mongo:27017/nefele-test nefele npm run test:api
